-- MySQL Script generated by MySQL Workbench
-- Tue Apr 20 00:27:06 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema BME
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema BME
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `BME` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `BME` ;

-- -----------------------------------------------------
-- Table `BME`.`Patient`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `BME`.`Patient` (
  `patient_id` VARCHAR(500) NOT NULL,
  `PatientName` VARCHAR(255) NULL DEFAULT NULL,
  `BirthDate` DATE NULL DEFAULT NULL,
  `Gender` VARCHAR(255) NULL DEFAULT NULL,
  `EnthnicGroup` VARCHAR(255) NULL DEFAULT NULL,
  PRIMARY KEY (`patient_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `BME`.`Study`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `BME`.`Study` (
  `StudyID` VARCHAR(255) NOT NULL,
  `StudyDate` DATE NULL DEFAULT NULL,
  `StudyDescription` VARCHAR(50) NULL DEFAULT NULL,
  `TotalSeries` INT NULL DEFAULT NULL,
  `Patient_patient_id` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`StudyID`),
  INDEX `patient_id_idx` (`Patient_patient_id` ASC) VISIBLE,
  CONSTRAINT `patient_id`
    FOREIGN KEY (`Patient_patient_id`)
    REFERENCES `BME`.`Patient` (`patient_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `BME`.`Series`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `BME`.`Series` (
  `series_id` VARCHAR(255) NOT NULL,
  `Study_StudyID` VARCHAR(255) NULL DEFAULT NULL,
  `series_number` INT NULL,
  `Seriescol` VARCHAR(45) NULL,
  PRIMARY KEY (`series_id`),
  INDEX `StudyInstanceUID_idx` (`Study_StudyID` ASC) VISIBLE,
  CONSTRAINT `StudyInstanceUID`
    FOREIGN KEY (`Study_StudyID`)
    REFERENCES `BME`.`Study` (`StudyID`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `BME`.`CT_Image`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `BME`.`CT_Image` (
  `ct_image_id` INT NOT NULL AUTO_INCREMENT,
  `pixel_data` VARCHAR(255) NULL DEFAULT NULL,
  `position` INT NULL DEFAULT NULL,
  `orientation` VARCHAR(50) NULL DEFAULT NULL,
  `number_of_exposure` INT NULL DEFAULT NULL,
  `reference_UID` INT NULL DEFAULT NULL,
  `pixel_spacing` VARCHAR(255) NULL DEFAULT NULL,
  `Series_series_id` VARCHAR(255) NOT NULL,
  INDEX `fk_CT_Image_Series1_idx` (`Series_series_id` ASC) VISIBLE,
  PRIMARY KEY (`ct_image_id`),
  CONSTRAINT `fk_CT_Image_Series1`
    FOREIGN KEY (`Series_series_id`)
    REFERENCES `BME`.`Series` (`series_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `BME`.`Dose_series`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `BME`.`Dose_series` (
  `Dose_series_id` INT NOT NULL,
  `Series_series_id` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`Dose_series_id`),
  INDEX `fk_Dose_series_Series1_idx` (`Series_series_id` ASC) VISIBLE,
  CONSTRAINT `fk_Dose_series_Series1`
    FOREIGN KEY (`Series_series_id`)
    REFERENCES `BME`.`Series` (`series_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `BME`.`RT_DVH`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `BME`.`RT_DVH` (
  `RT_DVH_id` INT NOT NULL AUTO_INCREMENT,
  `DVHDoseScaling` VARCHAR(50) NOT NULL,
  `DVHMaximumDose` FLOAT NOT NULL,
  `DVHMeanDose` FLOAT NOT NULL,
  `DVHMinimumDose` FLOAT NOT NULL,
  `DVHReferencedROI` VARCHAR(50) NOT NULL,
  `DVHType` VARCHAR(50) NOT NULL,
  `DVHVolumeUnits` VARCHAR(50) NOT NULL,
  `DoseType` VARCHAR(50) NOT NULL,
  `DoseUnits` VARCHAR(50) NOT NULL,
  `DVHData` LONGTEXT NOT NULL,
  `fk_dose_id_id` VARCHAR(500) NULL DEFAULT NULL,
  `fk_patient_id_id` VARCHAR(500) NULL DEFAULT NULL,
  `fk_series_id_id` VARCHAR(500) NULL DEFAULT NULL,
  `fk_study_id` VARCHAR(500) NULL DEFAULT NULL,
  PRIMARY KEY (`RT_DVH_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `BME`.`Dose`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `BME`.`Dose` (
  `Dose_id` INT NOT NULL,
  `NumberOfReferPlan` INT NOT NULL,
  `NumberOfDVH` INT NOT NULL,
  `NumberOfStructRoI` FLOAT NOT NULL,
  `Dose_series_id` INT NOT NULL,
  `RT_DVH_id` INT NOT NULL,
  PRIMARY KEY (`Dose_id`),
  INDEX `fk_Dose_Dose_series_idx` (`Dose_series_id` ASC) VISIBLE,
  INDEX `fk_Dose_RT_DVH1_idx` (`RT_DVH_id` ASC) VISIBLE,
  CONSTRAINT `fk_Dose_Dose_series`
    FOREIGN KEY (`Dose_series_id`)
    REFERENCES `BME`.`Dose_series` (`Dose_series_id`),
  CONSTRAINT `fk_Dose_RT_DVH1`
    FOREIGN KEY (`RT_DVH_id`)
    REFERENCES `BME`.`RT_DVH` (`RT_DVH_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `BME`.`OrganAtRisk`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `BME`.`OrganAtRisk` (
  `OAR_id` INT NOT NULL,
  `CentroidOfOrgan` VARCHAR(45) NULL DEFAULT NULL,
  `VolumeOfOrgan` INT NULL DEFAULT NULL,
  PRIMARY KEY (`OAR_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `BME`.`Planning_Target_Volumes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `BME`.`Planning_Target_Volumes` (
  `PTV_id` INT NOT NULL,
  `VoxelOfPTV` VARCHAR(45) NULL DEFAULT NULL,
  `VolumeOfPTV` INT NULL DEFAULT NULL,
  PRIMARY KEY (`PTV_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `BME`.`Overlap_Volume_Histogram`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `BME`.`Overlap_Volume_Histogram` (
  `OVH_id` INT NOT NULL,
  `OAR_id` INT NULL DEFAULT NULL,
  `PTV_id` INT NULL DEFAULT NULL,
  `Bin_Interval` VARCHAR(45) NULL DEFAULT NULL,
  `Bin_Amount` INT NULL DEFAULT NULL,
  `Study_StudyID` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`OVH_id`),
  INDEX `OAR_id_idx` (`OAR_id` ASC) VISIBLE,
  INDEX `PTV_id_idx` (`PTV_id` ASC) VISIBLE,
  INDEX `fk_Overlap_Volume_Histogram_Study1_idx` (`Study_StudyID` ASC) VISIBLE,
  CONSTRAINT `OAR_id`
    FOREIGN KEY (`OAR_id`)
    REFERENCES `BME`.`OrganAtRisk` (`OAR_id`),
  CONSTRAINT `PTV_id`
    FOREIGN KEY (`PTV_id`)
    REFERENCES `BME`.`Planning_Target_Volumes` (`PTV_id`),
  CONSTRAINT `fk_Overlap_Volume_Histogram_Study1`
    FOREIGN KEY (`Study_StudyID`)
    REFERENCES `BME`.`Study` (`StudyID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `BME`.`StructSet`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `BME`.`StructSet` (
  `StructNo` VARCHAR(255) NOT NULL,
  `NumberOfROIObservations` INT NULL DEFAULT NULL,
  `NumberOfReferFrame` INT NULL DEFAULT NULL,
  `NumberOfStructSetROI` INT NULL,
  `Series_series_id` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`StructNo`),
  INDEX `fk_StructSet_Series1_idx` (`Series_series_id` ASC) VISIBLE,
  CONSTRAINT `fk_StructSet_Series1`
    FOREIGN KEY (`Series_series_id`)
    REFERENCES `BME`.`Series` (`series_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `BME`.`RT_Contour`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `BME`.`RT_Contour` (
  `RT_Contour_id` INT NOT NULL AUTO_INCREMENT,
  `ContourGeometricType` VARCHAR(50) NULL,
  `NumberOfContourPoints` INT NULL,
  `ContourData` LONGTEXT NULL,
  `ReferencedSOPClassUID` VARCHAR(50) NOT NULL,
  `ReferencedSOPInstanceUID` VARCHAR(50) NOT NULL,
  `fk_structureset_id_id` INT NULL,
  `dose_series_ID` INT NULL,
  `Dose_id` INT NULL,
  `StructSet_StructNo` VARCHAR(255) NULL,
  `patient_id` VARCHAR(500) NULL,
  `series_id` VARCHAR(500) NULL,
  `study_id` VARCHAR(500) NULL,
  PRIMARY KEY (`RT_Contour_id`),
  INDEX `fk_RT_Contour_Dose1_idx` (`Dose_id` ASC) VISIBLE,
  INDEX `fk_RT_Contour_StructSet1_idx` (`StructSet_StructNo` ASC) VISIBLE,
  CONSTRAINT `fk_RT_Contour_Dose1`
    FOREIGN KEY (`Dose_id`)
    REFERENCES `BME`.`Dose` (`Dose_id`),
  CONSTRAINT `fk_RT_Contour_StructSet1`
    FOREIGN KEY (`StructSet_StructNo`)
    REFERENCES `BME`.`StructSet` (`StructNo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `BME`.`RT_ROI`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `BME`.`RT_ROI` (
  `RT_ROI_ID` INT NOT NULL,
  `Volume` FLOAT NOT NULL,
  `TotalContours` INT NOT NULL,
  `fk_structureset_id_id` INT NOT NULL,
  `fk_patient_id_id` INT NOT NULL,
  `fk_study_id_id` INT NOT NULL,
  `fk_series_id_id` INT NOT NULL,
  `fk_user_id_id` INT NOT NULL,
  `ROINumber` VARCHAR(50) CHARACTER SET 'utf8' NOT NULL,
  `Dose_id` INT NOT NULL,
  PRIMARY KEY (`RT_ROI_ID`),
  INDEX `fk_RT_ROI_Dose1_idx` (`Dose_id` ASC) VISIBLE,
  CONSTRAINT `fk_RT_ROI_Dose1`
    FOREIGN KEY (`Dose_id`)
    REFERENCES `BME`.`Dose` (`Dose_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `BME`.`Similarity`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `BME`.`Similarity` (
  `similarity_id` INT NOT NULL,
  `DBStudy_id` INT NULL DEFAULT NULL,
  `Similarity` DECIMAL(2,0) NULL DEFAULT NULL,
  `OVHDissimilarity` DECIMAL(2,0) NULL DEFAULT NULL,
  `STSDissimilarity` DECIMAL(2,0) NULL DEFAULT NULL,
  `TargetOAR` VARCHAR(45) NULL DEFAULT NULL,
  `Study_StudyID` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`similarity_id`),
  INDEX `fk_Similarity_Study1_idx1` (`Study_StudyID` ASC) VISIBLE,
  CONSTRAINT `fk_Similarity_Study1`
    FOREIGN KEY (`Study_StudyID`)
    REFERENCES `BME`.`Study` (`StudyID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `BME`.`Spatial_Target_Signature`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `BME`.`Spatial_Target_Signature` (
  `STS_id` INT NOT NULL,
  `OAR_id` INT NULL DEFAULT NULL,
  `PTV_id` INT NULL DEFAULT NULL,
  `Patient_id` VARCHAR(255) NULL DEFAULT NULL,
  `Interval_radial` VARCHAR(45) NULL DEFAULT NULL,
  `Radial_of_Voxel_Oc` DECIMAL(2,0) NULL DEFAULT NULL,
  `Interval_azimuth` VARCHAR(45) NULL DEFAULT NULL,
  `Azimuth_of_vector_Oc` DECIMAL(2,0) NULL DEFAULT NULL,
  `Interval_elevation` VARCHAR(45) NULL DEFAULT NULL,
  `Elevation_of_Vector_Oc` DECIMAL(2,0) NULL DEFAULT NULL,
  PRIMARY KEY (`STS_id`),
  INDEX `OAR_id_idx` (`OAR_id` ASC) VISIBLE,
  INDEX `PTV_id_idx` (`PTV_id` ASC) VISIBLE,
  INDEX `OAR_cons_idx` (`OAR_id` ASC) VISIBLE,
  INDEX `PTV_cons_idx` (`PTV_id` ASC) VISIBLE,
  CONSTRAINT `OAR_cons`
    FOREIGN KEY (`OAR_id`)
    REFERENCES `BME`.`OrganAtRisk` (`OAR_id`),
  CONSTRAINT `PTV_cons`
    FOREIGN KEY (`PTV_id`)
    REFERENCES `BME`.`Planning_Target_Volumes` (`PTV_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `BME`.`ROIObservation`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `BME`.`ROIObservation` (
  `Observation_Numer` VARCHAR(10) NULL,
  `Referenced_ROI_Number` VARCHAR(20) NULL,
  `ROI_Observation_Label` VARCHAR(255) NULL,
  `StructSet_StructNo` VARCHAR(255) NOT NULL,
  INDEX `fk_ROIObservation_StructSet1_idx` (`StructSet_StructNo` ASC) VISIBLE,
  CONSTRAINT `fk_ROIObservation_StructSet1`
    FOREIGN KEY (`StructSet_StructNo`)
    REFERENCES `BME`.`StructSet` (`StructNo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `BME`.`ReferFrame`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `BME`.`ReferFrame` (
  `FrameOfReferenceUID` VARCHAR(255) NOT NULL,
  `StructSet_StructNo` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`FrameOfReferenceUID`),
  INDEX `fk_ReferFrame_StructSet1_idx` (`StructSet_StructNo` ASC) VISIBLE,
  CONSTRAINT `fk_ReferFrame_StructSet1`
    FOREIGN KEY (`StructSet_StructNo`)
    REFERENCES `BME`.`StructSet` (`StructNo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `BME`.`ReferStudy`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `BME`.`ReferStudy` (
  `Referenced_SOP_Instance_UID` VARCHAR(255) NOT NULL,
  `Referenced_SOP_Class_UID` VARCHAR(255) CHARACTER SET 'DEFAULT' NOT NULL,
  `ReferFrame_FrameOfReferenceUID` VARCHAR(255) NOT NULL,
  INDEX `fk_ReferStudy_ReferFrame1_idx` (`ReferFrame_FrameOfReferenceUID` ASC) VISIBLE,
  PRIMARY KEY (`Referenced_SOP_Instance_UID`),
  CONSTRAINT `fk_ReferStudy_ReferFrame1`
    FOREIGN KEY (`ReferFrame_FrameOfReferenceUID`)
    REFERENCES `BME`.`ReferFrame` (`FrameOfReferenceUID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `BME`.`ReferSeries`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `BME`.`ReferSeries` (
  `Series_Instance_UID` VARCHAR(255) NOT NULL,
  `ReferStudy_Referenced_SOP_Instance_UID` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`Series_Instance_UID`),
  INDEX `fk_ReferSeries_ReferStudy1_idx` (`ReferStudy_Referenced_SOP_Instance_UID` ASC) VISIBLE,
  CONSTRAINT `fk_ReferSeries_ReferStudy1`
    FOREIGN KEY (`ReferStudy_Referenced_SOP_Instance_UID`)
    REFERENCES `BME`.`ReferStudy` (`Referenced_SOP_Instance_UID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `BME`.`ContourImage`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `BME`.`ContourImage` (
  `Referenced_SOP_Class_UID` VARCHAR(255) NOT NULL,
  `Referenced_SOP_Instance_UID` VARCHAR(255) NOT NULL,
  `ReferSeries_Series_Instance_UID` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`Referenced_SOP_Instance_UID`),
  INDEX `fk_ContourImage_ReferSeries1_idx` (`ReferSeries_Series_Instance_UID` ASC) VISIBLE,
  CONSTRAINT `fk_ContourImage_ReferSeries1`
    FOREIGN KEY (`ReferSeries_Series_Instance_UID`)
    REFERENCES `BME`.`ReferSeries` (`Series_Instance_UID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
